config/routes.rb
Seatyourself::Application.routes.draw do
  root :to => 'home#index'
  resources :users, :exclude => [:index]
  resources :reservations
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :restaurants, :exclude => [:index]

end

app/models/categories.rb
class Categories < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :restaurants

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :restaurants

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :user

  belongs_to :user
  belongs_to :timeslots


end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :city, :description, :district, :name, :street_address, :tables, :manager, :opens_at, :closes_at

  validates :description, :street_address, :tables, :district, :opens_at, :closes_at, :presence => true
  validates :name, :presence => true, :uniqueness => true

  has_many :timeslots
  has_and_belongs_to_many :categories
  belongs_to :manager, :class_name => 'User'

  def generate_two_weeks_of_datetimes(restaurant)
  		@date = Date.today
   		date_options = {}
    	14.times do
    		@datetime_option = DateTime.new(@date.year, @date.mon, @date.mday, restaurant.opens_at, 0, 0, '-4')
      		until @datetime_option.hour == restaurant.closes_at
        		date_options["#{@datetime_option.strftime("%A, %B %-d at %-I:%M %p")}"] = @datetime_option
        		@datetime_option += 1.hours
      		end
      		@date += 1.days
    	end
    	date_options
	end
end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base
  attr_accessible :start_time

  has_many :reservations
  belongs_to :restaurant

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation, :phone

  validates :first_name, :last_name, :presence => true
  validates :email, :presence => true, :uniqueness => true
  validates :phone, :presence => true, :uniqueness => true
  validates_presence_of :password, :on => :create

  has_many :reservations
  has_secure_password
  has_many :restaurants, :foreign_key => 'manager_id'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  # around_filter :set_time_zone

  # def set_time_zone
  #   old_time_zone = Time.zone
  #   Time.zone = current_user.time_zone if logged_in?
  #   yield
  # ensure
  #   Time.zone = old_time_zone
  # end

  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@restaurant = Restaurant.all
		if params[:category] != nil
			
		end
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	def create
		ts_params = params[:timeslot]
		ts_params['start_time'] = ts_params['start_time'].to_time
		# first_or_create does fancy stuff (look it up)
		@slot = Timeslot.where(ts_params).first_or_create!
		@restaurant = Restaurant.find(ts_params[:restaurant_id])

		if @slot.reservations.count < @restaurant.tables
			@slot.reservations.create(:user => current_user)
			redirect_to user_path(current_user), notice: 'Your reservation has been saved.'
		else
			#render restaurant_path(@restaurant), notice: 'You cannot book at this time.'
		end

	end

	# def create
	# 	@reservation = Reservation.new(:restaurant_id => 1, :slot_id => "1")
		
	# 	@slot = Timeslot.where(:slot => "Monday", :restaurant_id => 1).first
		
	# 	if @slot != nil
	# 		if Reservation.where(:slot => @slot).count < 10
	# 			@reservation.save
	# 			redirect_to user_path(current_user), notice: 'Your reservation has been saved.'
	# 		else
	# 			render restaurant_path, notice: 'You cannot book at this time.'
	# 		end
	# 	else
	# 		Timeslot.create(:slot => "Monday")
	# 		@reservation.save
	# 		redirect_to user_path(current_user), notice: 'Your reservation has been saved.'
	# 	end

	# end
end

# @reservation = Reservation.build(params[:reservation])

# @slot = Timeslot.where(:slot => params[:reservation][:slot] AND :restaurant_id => params[:restaurant_id]).first

# if Reservation.where(:slot => params[:reservation][:slot]).count < 10 #Get the restaurant table count

# Timeslot.create(params[:slot])

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new  
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    unless @restaurant.manager == current_user
      raise ActionController::RoutingError.new('Forbidden')
    end
  end

  def create
    @restaurant = Restaurant.new(params[:restaurant])
    @restaurant.manager = current_user

    if @restaurant.save
      redirect_to @restaurant, notice: 'Your restaurant was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update_attributes(params[:restaurant])
      redirect_to @restaurant, notice: 'Your restaurant was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to root_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
	end

	def create
		user = User.find_by_email(params[:email])

		if user
			if user && user.authenticate(params[:password])
				session[:user_id] = user.id
				redirect_to user, :notice => "Logged in!"
			else
				flash.now[:alert] = "Invalid email or password"
				render 'users/new'
			end
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new  
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      raise ActionController::RoutingError.new('Forbidden')
    end
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to @user, notice: 'Your account was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'Your account was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/reservations_helper.rb
module ReservationsHelper

end

app/helpers/restaurants_helper.rb
module RestaurantsHelper

end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>SeatYourself</h1>
<h2>Please select a category:</h2>

<%- @restaurant.each do |restaurant| %>
	<div class ="restaurant-block">
		<h3><%= link_to restaurant.name, restaurant%></h3>
		<h4>Location</h4>
			<p>
				<strong>City:</strong> <%= restaurant.city %><br>
				<strong>Address:</strong> <%= restaurant.street_address %><br>
				<strong>District:</strong> <%= restaurant.district %>
			</p>
		<h4>About <% restaurant.name %></h4>
			<p>
				<strong>Food Category:</strong> <%= restaurant.categories.map {|category| category.name}.join(", ") %><br>
				<strong>Total Tables:</strong> <%= restaurant.tables %><br>
				<strong>Description:</strong> <%= restaurant.description %>
			</p>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="userinfo">
	<% if current_user %>
		Welcome back, <%= current_user.first_name %>! 
		<%= link_to "Log out", session_path("current"), :method => :delete %>
	<% else %>
		<%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
	<% end %>
</p>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>

  <% if @restaurant.errors.any? %>
	<div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br />
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :district %><br />
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label :tables %><br />
    <%= f.text_field :tables %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_reservation.html.erb
<% reservation = Reservation.new %>
<%= form_for(reservation) do |f| %>

  <% if reservation.errors.any? %>
	<div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag 'timeslot[restaurant_id]', @restaurant.id %>

  <div class="field">
    <%= f.label "Test" %><br />
    <%= select_tag 'timeslot[start_time]', options_from_collection_for_select(@restaurant.generate_two_weeks_of_datetimes(@restaurant), :last, :first ) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Update Your Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/new.html.erb
<h1>Setup Your Restaurant on SeatYourself</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<% if current_user == @restaurant.manager %>
<h1>Manage <%= @restaurant.name %></h1>
<% else %>
<h1><%= @restaurant.name %></h1>
<% end %> 

<p class="notice"><%= notice %></p>

<div class="info">
	<h3>Location</h3>
	<p>
		<strong>City:</strong> <%= @restaurant.city %><br>
		<strong>Address:</strong> <%= @restaurant.street_address %><br>
		<strong>District:</strong> <%= @restaurant.district %>
	</p>
	<h3>About <% @restaurant.name %></h3>
	<p>
		<strong>Food Category:</strong> <%= @restaurant.categories.map {|category| category.name}.join(", ") %><br>
		<strong>Total Tables:</strong> <%= @restaurant.tables %><br>
		<strong>Description:</strong> <%= @restaurant.description %>
	</p>
</div>

<%= render "reservation" if current_user %>

<% if current_user == @restaurant.manager %>
<%= link_to "Edit", edit_restaurant_path(@restaurant) %> 
<% else %>
	
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <% if @user.errors.any? %>
	<div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Update Your Account</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign up for SeatYourself</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<% if current_user == @user %>
<h1>Your Profile</h1>
<% else %>
<h1><%= @user.first_name %>'s Profile</h1>
<% end %> 

<p class="notice"><%= notice %></p>

<% if current_user == @user %>
<%= link_to "Edit Your Profile", edit_user_path(@user) %> 
<div class="editable-data">
		<h3>Your Information</h3>
	<p>
		<strong>First Name:</strong> <%= @user.first_name %><br>
		<strong>Last Name:</strong> <%= @user.last_name %><br>
		<strong>Email:</strong> <%= @user.email %><br>
		<strong>Phone:</strong> <%= @user.phone %><br>
	</p>
</div>
<% else %> 

<div class="info">
	<h3>About <%= @user.first_name %></h3>
	<p>
		<strong>Name:</strong> <%= @user.first_name %><br>
		<strong>Ratings:</strong>
	</p>
</div>

<% end %>